# syntax=docker/dockerfile:1

FROM python:3.12-slim-bookworm

WORKDIR /opt/app

COPY . .

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
RUN pip install --no-cache-dir -r requirements.lock

EXPOSE 80

ENTRYPOINT ["sanic"]
CMD ["bypass.server:make_app", "--bind=0.0.0.0:80", "--workers=2", "-k aiohttp.GunicornWebWorker"]
